- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/api/v5/api_controller.rb
- app/controllers/api/v5/courses_controller.rb
- app/controllers/api/v5/departments_controller.rb
- app/sweepers/base_sweeper.rb
- app/sweepers/courses_sweeper.rb
- config/application.rb
- config/environments/production.rb
implements action caching for xml views only.
> Action caching

- app/assets/javascripts/views/schedules.js
- app/assets/stylesheets/courses.css
- app/assets/stylesheets/header.css
- app/assets/stylesheets/index.css
- app/views/static/index.html.erb
- public/search.svg
- Pretty search bar
- Fix schedule navigation error when no schedules present
- Fix course highlighting for closed sections
> UI improvements

- app/assets/javascripts/views/courses.js
> makes noon display as pm

- app/assets/javascripts/views/schedules.js
-Added missing semicolons.
-Improved nomenclature: changed show() function to showSchedule(), next() to nextSchedule(), previous to prevSchedule().
-Changed target.querySelector calls to document.getElementById.
> Cleanup for issue #139

- app/assets/javascripts/controllers/courses/helpers.js
> Fix noon display bug

- app/assets/javascripts/controllers/schedules/controller.js
- app/assets/stylesheets/schedule.css
> Fix CRN selection bug

- .gitignore
- Dockerfile
- app/views/layouts/application.html.erb
- config/environments/production.rb
- nginx/Dockerfile
- nginx/nginx.conf
In nginx.conf:
New SSL configuration
Enables cache directory
In production.rb:
Enables sendfile header
In application.html.erb:
Updates title to 2017
In Dockerfile:
Updates phantomjs link
In .gitignore:
Adds .env
> Update Staging SSL Configuration

- README.md
Significantly beefs up our README. Adds descriptions of different services (existing and in development), projects that use the YACS API, a much needed full description, and other misc. info,
> Now THAT'S a README

- app/controllers/api/v5/api_controller.rb
- app/controllers/api/v5/courses_controller.rb
- app/controllers/api/v5/sections_controller.rb
- config/routes.rb
- spec/requests/api/v5/courses_spec.rb
- spec/requests/api/v5/sections_spec.rb
Added two tests for seats_taken and seats
Used strong parameters to allow testing for sections
Added update action for sections_controller.rb
> Admin API Tests

- app/controllers/api/v5/courses_controller.rb
- app/controllers/api/v5/departments_controller.rb
- app/controllers/api/v5/schools_controller.rb
- app/controllers/api/v5/sections_controller.rb
- config/routes.rb
- spec/models/department_spec.rb
- spec/requests/api/v5/courses_spec.rb
- spec/requests/api/v5/departments_spec.rb
- spec/requests/api/v5/schools_spec.rb
- spec/requests/api/v5/sections_spec.rb
All tests for sections, courses, departments, and schools for create, update, and destroy
have been added.
> Admin API Create, Destroy, and Update Tests

- app/controllers/api/v5/courses_controller.rb
- app/controllers/api/v5/departments_controller.rb
- app/controllers/api/v5/schools_controller.rb
- app/controllers/api/v5/sections_controller.rb
- config/routes.rb
- spec/requests/api/v5/courses_spec.rb
- spec/requests/api/v5/departments_spec.rb
- spec/requests/api/v5/schools_spec.rb
- spec/requests/api/v5/sections_spec.rb
Responses returned by GET/POST/PUT requests have been rendered, validated, and displayed by all tests within courses_spec.rb, schools_spec.rb, sections_spec.rb, and departments_spec.rb.
Additionally, no_content headers/responses have been replaced with calls to the show function.
> Admin API Response Validation for PUT/POST/GET Requests

- app/controllers/api/v5/courses_controller.rb
allows searching of strings containing hyphens (professors' names)
> change in courses_controller.rb

- .gitignore
- app/consumers/application_consumer.rb
- app/models/section.rb
- app/views/api/v5/schedules/index.json.jbuilder
- app/views/api/v5/sections/_sections.json.jbuilder
- db/migrate/20180228222337_add_periods_location_to_sections.rb
- db/schema.rb
White-listed location and added location column to the data base.
> Added back-end functionality to send location to frontend

- app/views/layouts/application.html.erb
Really pulled out all the stops on this one
> Updated <title> tag to display correct year

- app/serializers/course_serializer.rb
- app/serializers/department_serializer.rb
- app/serializers/instructor_serializer.rb
- app/serializers/listing_serializer.rb
- app/serializers/section_serializer.rb
- app/serializers/session_serializer.rb
- app/serializers/subject_serializer.rb
These are the new serializers for each model.
> New Serializers

- .all-contributorsrc
Adding myself to contributors document for contributing to docs. Hoping to eventually contribute to other areas as well
> Added @a1liu to contributors

- adapters/nyu/.gitignore
- adapters/nyu/README.md
- adapters/nyu/gallatin/README.md
- adapters/nyu/gallatin/main.py
- adapters/nyu/sites.md
Wrote a few documentation files and added a placeholder file for the gallatin adapter
> Added NYU adapter folder

- pipelines/nyu/adapters/gallatin/README.md
- pipelines/nyu/adapters/gallatin/apitrans.py
- pipelines/nyu/adapters/gallatin/gallatin api.md
Also cleaning up some markdown
> Fix return value of get_query()

- pipelines/nyu/adapters/gallatin/reqhandler.py
Work done on do_GET() so that the server sends the requests to NYU and sends them back to YACS.
> Server can send requests, yo

- pipelines/nyu/adapters/gallatin/src/jsontrans.py
- pipelines/nyu/adapters/gallatin/src/reqhandler.py
- pipelines/nyu/adapters/gallatin/test.py
Doing bug testing so that Gallatin Adapter is functional.
> Bug Fixes for Gallatin Adapter

- web/src/app/listing/component.html
- web/src/app/listing/component.ts
- web/src/app/sidebar/interested-courses/component.html
- web/src/app/sidebar/interested-courses/component.scss
- web/src/app/sidebar/interested-courses/component.ts
Should work. Couldn't find any more cases of the error I was getting where it randomly wasn't working as expected.
> Added sidebar message for no description

- core/app/models/course.rb
- core/app/models/listing.rb
- core/app/resources/listing_resource.rb
- web/src/app/header/component.html
- web/src/app/header/component.ts
- web/src/app/listing-view/component.ts
- web/src/app/listing/component.scss
- web/src/app/schedule-view/component.html
- web/src/app/schedule-view/component.scss
- web/src/app/sidebar/interested-courses/component.scss
- web/src/styles.scss
This PR addresses some issues brought up in our first round of usability feedback from the HCI report.
Issues resolved:
- Search not working (#375)
- Comments out login link (no issue)
- Clear button not working (#376)
- Confusing layout of buttons on the schedule page (no issue)
- Clicking a listing title (#377 , no fix required)
- Minor code cleanup
> Usability Feedback 1

- web/src/app/app.component.scss
- web/src/app/sidebar/component.scss
Made a larger sidebar button.
Made the sidebar able to independently scroll.
Sidebar no longer increases the height of the page.
Sidebar and button made sticky.
For addressing issues #402 and #393
> Independently scrolling sidebar and larger sidebar button

- package-lock.json
- web/src/app/app-router/module.ts
- web/src/app/app.component.html
- web/src/app/app.component.scss
- web/src/app/app.module.ts
- web/src/app/footer/component.ts
- web/src/app/header/component.html
- web/src/app/listing-detail/component.html
- web/src/app/listing-detail/component.spec.ts
- web/src/app/listing-detail/component.ts
- web/src/app/listing-detail/module.ts
- web/src/app/listing/component.html
- web/src/app/listing/component.scss
- web/src/app/listing/module.ts
- web/src/app/sidebar/component.scss
Added a new form component with multiple input fields in order to modify a given listing. 
Each listing has an edit button that can be used to navigate to the new view.
Input fields are not functional yet.
UI is not formatted, elements are just displayed to show the component properly links to a listing.
> Created listing-detail module for admin

- web/src/app/app.component.html
- web/src/app/app.component.scss
- web/src/app/app.component.ts
- web/src/app/footer/component.html
- web/src/app/header/component.html
- web/src/app/listing-view/component.html
- web/src/app/listing/component.html
- web/src/app/listing/component.scss
- web/src/app/listing/section/component.scss
- web/src/app/school-view/component.html
- web/src/app/school-view/component.scss
- web/src/app/sidebar/component.html
- web/src/app/sidebar/component.scss
- web/src/app/sidebar/interested-courses/component.html
- web/src/app/sidebar/interested-courses/component.scss
- web/src/index.html
- web/src/styles.scss
This PR cleans up a number of layout issues. We now use flexbox for the main page layout in a less hacky way.  Also cleans up a few other random css issues and dead classes that were bothering me.
Addesses #406 by hiding the section status on mobile for now.
> Layout cleanup

- web/src/app/app.component.scss
- web/src/app/models/schedule-set.ts
- web/src/app/schedule-view/component.html
- web/src/app/schedule-view/component.ts
Addresses issue #418 
also addresses issue #383 because apparently doing a commit automatically puts it in any pull request you currently had open
> Modified sidebar toggler, fixed sidebar scroll

- web/src/app/footer/component.html
I changed the version text in the footer :D
> Changed version to 0.12 Angular

- core/db/migrate/20190326210039_alt_seats_and_seatstaken_to_nullable.rb
> Alt seats and seats_taken column to be nullable

- core/db/structure.sql
Issue https://github.com/YACS-RCOS/yacs/issues/436
> Fix Issue #436

- web/src/app/header/component.html
Just added a display: none to the link until this gets implemented.
> hid 'Topics' button

- core/Dockerfile
> Remove phantomjs dependency

- web/package.json
Fixed version issue with scss loader
> Fix version issue with scss loader

- docker-compose.pipeline.yml
> fix for prod deployment, missing required file (docker-compose pipeline fix)

- core/config/database.yml
This will increase the number of db connections available to match the number of threads
> increased database pool size

- bin/yacs-purge-development
- bin/yacs-purge-production
- docker-compose.development.yml
http://kvm3.cs.rpi.edu deployed for check. Looks good to me, want to get another set of eyes before we deploy to prod.
> Fall 2020 Deployment
